name: github-actions-demo-05
run-name: ${{ github.actor }} Additional features 🎉
on: workflow_dispatch

jobs:
  Get-Emails-From-Json:
    runs-on: ubuntu-latest
    outputs:
      people: ${{ steps.get_emails.outputs.people }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Get Emails
        id: get_emails
        run: |
          {
            echo 'people<<EOF'
            jq -c '.' emailsMap.json
            echo EOF
          } >> "$GITHUB_OUTPUT"

  Send-Emails-Using-Matrix:
    needs: [Get-Emails-From-Json]
    strategy:
      matrix:
        person_list: ${{ fromJson(needs.Get-Emails-From-Json.outputs.people) }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "GitHub Actions Demo 04 - App"
          html_body: "Hi ${{ matrix.person_list.name }} This is a test email from GitHub Actions."
          to: ${{ matrix.person_list.email }}
          from: "Demo App"
          attachments: ./attach_file.txt
          secure: true
          ignore_cert: true

      - name: Summary
        run: echo "### IT WORKS! :rocket:" >> $GITHUB_STEP_SUMMARY
