name: github-actions-demo-05
run-name: ${{ github.actor }} Additional features 🎉
on: workflow_dispatch

jobs:
  Get-Emails-From-Json:
    runs-on: ubuntu-latest
    outputs:
      people: ${{ steps.get_emails.outputs.people }}
      person_list: ${{ steps.get_emails_list.outputs.person_list }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt update
          sudo apt install jq

      - name: Get Emails
        id: get_emails
        run: |
          {
            echo 'people<<EOF'
            jq -c '.' emailsMap.json
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Get Emails List
        id: get_emails_list
        run: |
          {
            echo 'person_list<<EOF'
            jq -c '.[]' emailsMap.json
            echo EOF
          } >> "$GITHUB_OUTPUT"

  Send-Emails-Using-Matrix:
    needs: [Get-Emails-From-Json]
    strategy:
      matrix:
        person_info_list: ${{ fromJson(needs.Get-Emails-From-Json.outputs.people) }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "GitHub Actions Demo 04 - App"
          html_body: "Hi ${{ matrix.person_info_list.name }} This is a test email from GitHub Actions."
          to: ${{ matrix.person_info_list.email }}
          from: "Demo App"
          attachments: ./attach_file.txt
          secure: true
          ignore_cert: true

  Send-Emails-Using-For:
    needs: [Get-Emails-From-Json]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Send Mail using Script
        env:
          person_info_list: ${{ needs.Get-Emails-From-Json.outputs.person_list }}
        run: |
          for p in $person_info_list 
          do
            name = $(echo "$p" | jq -r '.name')
            body = "Hi $name This is a test email from GitHub Actions."
            mail = $(echo "$p" | jq -r '.email')
            python scripts/send_emails.py --username ${{ secrets.MAIL_USERNAME }} --password ${{ secrets.MAIL_PASSWORD_1 }} --from_address "Demo Script" --to_addresses "$email" --body "$body" --attachment_path attach_file.txt
          done
          echo "### IT WORKS! :rocket:" >> $GITHUB_STEP_SUMMARY
