name: github-actions-demo-06
run-name: ${{ github.actor }} Additional features 🎉
on: workflow_dispatch

jobs:
  Get-Emails-From-Json:
    runs-on: ubuntu-latest
    outputs:
      people: ${{ steps.get_emails.outputs.people }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Get Emails
        id: get_emails
        run: |
          {
            echo 'people<<EOF'
            jq -c '.' emailsMap.json
            echo EOF
          } >> "$GITHUB_OUTPUT"

  Send-Emails-Using-For:
    needs: [Get-Emails-From-Json]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Send Mail using Script
        env:
          person_info_list: ${{ needs.Get-Emails-From-Json.outputs.people }}
        run: |
          for p in $person_info_list 
          do
            name = $(echo "$p" | jq -r '.name')
            body = "Hi $name This is a test email from GitHub Actions."
            mail = $(echo "$p" | jq -r '.email')
            python scripts/send_emails.py --username ${{ secrets.MAIL_USERNAME }} --password ${{ secrets.MAIL_PASSWORD_1 }} --from_address "Demo Script" --to_addresses "$email" --body "$body" --attachment_path attach_file.txt
          done
          echo "### IT WORKS! :rocket:" >> $GITHUB_STEP_SUMMARY
