name: github-actions-demo-05
run-name: ${{ github.actor }} Additional features 🎉
on: workflow_dispatch

jobs:
  Get-Emails-From-Json:
    runs-on: ubuntu-latest
    outputs:
      people: ${{ steps.get_emails.outputs.people }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt update
          sudo apt install jq

      - name: Get Emails
        id: get_emails
        run: |
          {
            echo 'people<<EOF'
            jq -c '.[]' emailsMap.json
            echo EOF
          } >> "$GITHUB_OUTPUT"
          echo $people

  Send-Emails-Using-Matrix:
    needs: [Get-Emails-From-Json]
    strategy:
      matrix:
        person_info_list: ${{ format(needs.Get-Emails-From-Json.outputs.people) }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Mail
        run: |
          echo "Sending email to ${{ matrix.person_info_list.name }}"
          echo "Email sent to ${{ matrix.person_info_list.email }}"
      - name: Sumary
        run: echo "### IT WORKS! :rocket:" >> $GITHUB_STEP_SUMMARY
