name: github-actions-demo-06
run-name: ${{ github.actor }} Additional features 🎉
on: workflow_dispatch

jobs:
  Get-Emails-From-Json:
    runs-on: ubuntu-latest
    outputs:
      people: ${{ steps.get_emails.outputs.people }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Get Emails
        id: get_emails
        run: |
          {
            echo 'people<<EOF'
            jq -c '.[]' emailsMap.json
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"

  Send-Emails-Using-For:
    needs: [Get-Emails-From-Json]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Send Mail using Script
        env:
          person_info_list: ${{ needs.Get-Emails-From-Json.outputs.people }}
        run: |
          for person_info in $person_info_list" 
          do
            echo "Sending email to $person_info"
          done
          echo "### IT WORKS! :rocket:" >> $GITHUB_STEP_SUMMARY
